WITH MAX_COLONY_BY_YEAR AS (
  SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
  YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
  MC.MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV,
  ED.ID
FROM 
  ECOLI_DATA AS ED
JOIN 
  MAX_COLONY_BY_YEAR AS MC
  ON YEAR(ED.DIFFERENTIATION_DATE) = MC.YEAR
ORDER BY 
  YEAR, YEAR_DEV;